# .gitlab-ci.yml

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev
  - python -V
  - pip install --upgrade pip
  - pip install coverage
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - coverage run manage.py test
    - coverage report --fail-under=70
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml