image: python:3.13.3-alpine3.20

before_script:
  - python3 -m venv .venv
  - . .venv/bin/activate
  - pip install -r requirements.txt

stages:
  - style
  - test
  - docs

pylint:
  stage: style
  script:
    - pylint --fail-under=6 --ignore-paths="docs/*" **/*.py
    - echo "Pylint complete."
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days


pycodestyle:
  stage: style
  script:
    - pycodestyle --max-line-length=120 **/*.py
    - echo "Pycodestyle complete."
  artifacts:
    untracked: false
    when: on_failure
    expire_in: 30 days


python:
  stage: test
  script:
    - .venv/bin/python manage.py test
    - echo "Tests complete."
  artifacts:
    untracked: false
    when: on_failure
    expire_in: 30 days


sphinx:
  stage: docs
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs
    - sphinx-build -b html source build
    - echo "Sphinx documentation built."
  artifacts:
    paths:
      - docs/build/
    expire_in: 30 days
    when: on_success