# Generated by Django 5.2.15 on 2026-06-14 15:11

import apps.quiz.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Одиночный выбор"),
                            ("multiple", "Множественный выбор"),
                            ("text", "Текстовый"),
                            ("number", "Числовой"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "correct_number",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Правильное число"
                    ),
                ),
                (
                    "coefficient",
                    models.PositiveIntegerField(default=1, verbose_name="Коэффициент"),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=30, verbose_name="Время на ответ (сек)"
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        default=apps.quiz.models.generate_pin,
                        max_length=6,
                        unique=True,
                        verbose_name="PIN-код",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидание"),
                            ("in_progress", "Идёт игра"),
                            ("finished", "Завершена"),
                        ],
                        default="waiting",
                        max_length=15,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(default=False, verbose_name="Лобби закрыто"),
                ),
                (
                    "current_question",
                    models.IntegerField(default=0, verbose_name="Текущий вопрос"),
                ),
                (
                    "current_question_started_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время старта текущего вопроса",
                    ),
                ),
                (
                    "ready_for_next_question",
                    models.BooleanField(
                        default=False,
                        verbose_name="Все ответили, готово к переключению",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hosted_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Хост",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Отображаемое имя"
                    ),
                ),
                ("score", models.IntegerField(default=0, verbose_name="Счёт")),
                (
                    "is_answered",
                    models.BooleanField(
                        default=False, verbose_name="Ответил на текущий вопрос"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_participations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Игрок",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="quiz.gamesession",
                        verbose_name="Сессия",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Текст ответа")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название квиза"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "additional_info",
                    models.TextField(
                        blank=True, verbose_name="Дополнительная информация"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "time_limit",
                    models.IntegerField(
                        blank=True,
                        help_text="Ограничение по времени в минутах",
                        null=True,
                        verbose_name="Лимит времени (мин)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Черновик"), ("active", "Активен")],
                        default="draft",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалён"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes",
                        to="quiz.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_quizzes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Quizzes",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quiz.quiz",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="quiz.quiz",
                verbose_name="Квиз",
            ),
        ),
        migrations.CreateModel(
            name="QuizRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Версия")),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название ревизии"),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество вопросов"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Максимальный балл"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="quiz.quiz",
                        verbose_name="Квиз",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ревизия квиза",
                "verbose_name_plural": "Ревизии квиза",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Отображаемое имя"
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("max_score", models.IntegerField(default=0)),
                ("score_percent", models.FloatField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="quiz.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="quiz.quizrevision",
                        verbose_name="Ревизия квиза",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuizReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("wrong_answers", "Ошибка в вопросе или ответе"),
                            ("inappropriate", "Некорректный контент"),
                            ("offtopic", "Не относится к теме"),
                            ("technical_problem", "Техническая проблема"),
                            ("other", "Другое"),
                        ],
                        max_length=32,
                        verbose_name="Причина",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Новая"),
                            ("accepted", "Подтверждена"),
                            ("rejected", "Отклонена"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "admin_comment",
                    models.TextField(
                        blank=True, verbose_name="Комментарий администратора"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="quiz.quiz",
                        verbose_name="Квиз",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор жалобы",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_quiz_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Проверил",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="quiz.quizrevision",
                        verbose_name="Версия квиза",
                    ),
                ),
            ],
            options={
                "verbose_name": "Жалоба на квиз",
                "verbose_name_plural": "Жалобы на квизы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="quiz",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="quiz.quizrevision",
                verbose_name="Текущая ревизия",
            ),
        ),
        migrations.AddField(
            model_name="gamesession",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="quiz.quizrevision",
                verbose_name="Ревизия квиза",
            ),
        ),
        migrations.CreateModel(
            name="RevisionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Одиночный выбор"),
                            ("multiple", "Множественный выбор"),
                            ("text", "Текстовый"),
                            ("number", "Числовой"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "correct_number",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Правильное число"
                    ),
                ),
                (
                    "coefficient",
                    models.PositiveIntegerField(default=1, verbose_name="Коэффициент"),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=30, verbose_name="Время на ответ (сек)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quiz.quizrevision",
                        verbose_name="Ревизия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос ревизии",
                "verbose_name_plural": "Вопросы ревизии",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RevisionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Текст ответа")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.revisionquestion",
                        verbose_name="Вопрос ревизии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ ревизии",
                "verbose_name_plural": "Ответы ревизии",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GameAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Верно"),
                ),
                ("points", models.IntegerField(default=0, verbose_name="Баллы")),
                ("answered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="quiz.answer",
                        verbose_name="Выбранный ответ",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="quiz.gameparticipant",
                        verbose_name="Участник",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_answers",
                        to="quiz.gamesession",
                        verbose_name="Сессия",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_answers",
                        to="quiz.question",
                        verbose_name="Старый вопрос",
                    ),
                ),
                (
                    "revision_question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_answers",
                        to="quiz.revisionquestion",
                        verbose_name="Вопрос ревизии",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gameparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="unique_participant_per_session",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizrevision",
            unique_together={("quiz", "version")},
        ),
        migrations.AddConstraint(
            model_name="quizreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("quiz", "reporter"),
                name="unique_pending_quiz_report_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("question__isnull", False)),
                fields=("participant", "question"),
                name="unique_gameanswer_legacy_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revision_question__isnull", False)),
                fields=("participant", "revision_question"),
                name="unique_gameanswer_revision_question",
            ),
        ),
    ]
