# Generated by Django 5.1.4 on 2026-10-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameanswer",
            name="number_answer",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Числовой ответ"
            ),
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="text_answer",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текстовый ответ"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="correct_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Правильный текстовый ответ"
            ),
        ),
        migrations.AddField(
            model_name="revisionquestion",
            name="correct_text",
            field=models.TextField(
                blank=True, null=True, verbose_name="Правильный текстовый ответ"
            ),
        ),
    ]
