# Generated by Django 6.0.3 on 2026-05-02 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gameanswer',
            name='revision_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_answers', to='main.revisionquestion', verbose_name='Вопрос ревизии'),
        ),
        migrations.AlterField(
            model_name='gameanswer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_answers', to='main.question', verbose_name='Старый вопрос'),
        ),
        migrations.AddConstraint(
            model_name='gameanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('question__isnull', False)), fields=('participant', 'question'), name='unique_gameanswer_legacy_question'),
        ),
        migrations.AddConstraint(
            model_name='gameanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('revision_question__isnull', False)), fields=('participant', 'revision_question'), name='unique_gameanswer_revision_question'),
        ),
    ]
