"""Generated by Django 6.0.3 on 2026-04-28 22:00"""

# pylint: disable=invalid-name

from django.db import migrations, models


class Migration(migrations.Migration):
    """Вы всё правильно поняли"""
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="coefficient",
            field=models.PositiveIntegerField(default=1, verbose_name="Коэффициент"),
        ),
    ]
