# Generated by Django 5.1.4 on 2026-04-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('teacher', 'Учитель'), ('student', 'Ученик')], default='student', max_length=20, verbose_name='Роль'),
        ),
    ]
