# Generated by Django 6.0.3 on 2026-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_coefficient'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_question_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время старта текущего вопроса'),
        ),
    ]
