# Generated by Django 5.1.4 on 2026-06-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_gamesession_ready_for_next_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
    ]
