"""Generated by Django 6.0.3 on 2026-04-29 21:34"""

# pylint: disable=invalid-name

from django.db import migrations, models


class Migration(migrations.Migration):
    """Слишком важная информация"""
    dependencies = [
        ("main", "0003_gamesession_current_question_started_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameanswer",
            name="points",
            field=models.IntegerField(default=0, verbose_name="Баллы"),
        ),
    ]
