# Generated by Django 5.1.4 on 2026-05-07 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_gameanswer_points"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gameanswer",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="gameanswer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_answers",
                to="main.question",
                verbose_name="Старый вопрос",
            ),
        ),
        migrations.CreateModel(
            name="QuizRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="Версия")),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название ревизии"),
                ),
                (
                    "question_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество вопросов"
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Максимальный балл"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="main.quiz",
                        verbose_name="Квиз",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ревизия квиза",
                "verbose_name_plural": "Ревизии квиза",
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="gamesession",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessions",
                to="main.quizrevision",
                verbose_name="Ревизия квиза",
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="current_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="main.quizrevision",
                verbose_name="Текущая ревизия",
            ),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="main.quizrevision",
                verbose_name="Ревизия квиза",
            ),
        ),
        migrations.CreateModel(
            name="RevisionQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст вопроса")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "Одиночный выбор"),
                            ("multiple", "Множественный выбор"),
                            ("text", "Текстовый"),
                            ("number", "Числовой"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "correct_number",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Правильное число"
                    ),
                ),
                (
                    "coefficient",
                    models.PositiveIntegerField(default=1, verbose_name="Коэффициент"),
                ),
                (
                    "time_limit",
                    models.IntegerField(
                        default=30, verbose_name="Время на ответ (сек)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="main.quizrevision",
                        verbose_name="Ревизия",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос ревизии",
                "verbose_name_plural": "Вопросы ревизии",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="RevisionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Текст ответа")),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="main.revisionquestion",
                        verbose_name="Вопрос ревизии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ ревизии",
                "verbose_name_plural": "Ответы ревизии",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="gameanswer",
            name="revision_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_answers",
                to="main.revisionquestion",
                verbose_name="Вопрос ревизии",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("question__isnull", False)),
                fields=("participant", "question"),
                name="unique_gameanswer_legacy_question",
            ),
        ),
        migrations.AddConstraint(
            model_name="gameanswer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revision_question__isnull", False)),
                fields=("participant", "revision_question"),
                name="unique_gameanswer_revision_question",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizrevision",
            unique_together={("quiz", "version")},
        ),
    ]
