# Generated by Django 6.0.3 on 2026-05-12 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_gameanswer_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_answers', 'Ошибка в вопросе или ответе'), ('inappropriate', 'Некорректный контент'), ('offtopic', 'Не относится к теме'), ('technical_problem', 'Техническая проблема'), ('other', 'Другое')], max_length=32, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Новая'), ('accepted', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=16, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.quiz', verbose_name='Квиз')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор жалобы')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_quiz_reports', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='main.quizrevision', verbose_name='Версия квиза')),
            ],
            options={
                'verbose_name': 'Жалоба на квиз',
                'verbose_name_plural': 'Жалобы на квизы',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('quiz', 'reporter'), name='unique_pending_quiz_report_per_user')],
            },
        ),
    ]
