# Generated by Django 6.0.2 on 2026-05-19 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_quizreport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="gameparticipant",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="gameparticipant",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Отображаемое имя"
            ),
        ),
        migrations.AddField(
            model_name="quizresult",
            name="display_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Отображаемое имя"
            ),
        ),
        migrations.AlterField(
            model_name="gameparticipant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Игрок",
            ),
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="quiz_results",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="gameparticipant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("session", "user"),
                name="unique_participant_per_session",
            ),
        ),
    ]
