# Generated by Django 5.1.4 on 2026-05-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_backfill_display_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="ready_for_next_question",
            field=models.BooleanField(
                default=False, verbose_name="Все ответили, готово к переключению"
            ),
        ),
    ]
