# Generated by Django 5.2.15 on 2026-06-14 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Админ"),
                            ("teacher", "Учитель"),
                            ("student", "Ученик"),
                        ],
                        default="student",
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Администратор"),
                ),
                (
                    "is_banned",
                    models.BooleanField(default=False, verbose_name="Заблокирован"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
